using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.Serialization;
using Utility;

public class TerribleUiController : MonoBehaviour
{
    [SerializeField]
    private TextMeshProUGUI _weekdayText;
    
    [SerializeField]
    private TextMeshProUGUI _dayTimeText;

    [SerializeField]
    private TextMeshProUGUI _progressText;
    
    [SerializeField]
    private TextMeshProUGUI _startDateText;
    
    [SerializeField]
    private TextMeshProUGUI _deadlineText;
    
    [SerializeField]
    private TextMeshProUGUI _currentDateText;
    
    [SerializeField]
    private TextMeshProUGUI _daysLeftText;

    void Update()
    {
        _weekdayText.text = TimeManager.Instance.CurrentDayOfWeek.GetName();
        _dayTimeText.text = $"Day Time: {TimeManager.Instance.TimeOfDay:h\\:mm\\:ss}";
        _progressText.text = $"Progress: {(GameManager.Instance.GameProgress * 100.0):F3}%";
        
        _startDateText.text = $"Start Date: {TimeManager.Instance.StartDate}";
        _currentDateText.text = $"Current Date: {TimeManager.Instance.CurrentDate}";
        _deadlineText.text = $"Deadline: {TimeManager.Instance.Deadline}";
        
        _daysLeftText.text = $"Days left: {TimeManager.Instance.DaysLeft}";
    }
}
